name: libphonenumber
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/fonibo/libphonenumber

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  test: any
